##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..
LIBRARYNAME=iron3men
#
# List all of the subdirectories that we will compile.
#
DIRS=sample

include $(LEVEL)/Makefile.common
